# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      HOST: "localhost"
      PORT: 4000
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"